### ISSUE TITLE
Extended `sys` functions docs missing

### ISSUE THREAD

**Issue by larsgw** [Juris-M/citeproc-js-docs#21]
I saw some other `sys` functions in one of the demos, and it reminded me that the docs for the extended `sys` functions are missing, or at least here. `getAbbreviation` docs _are_ available in the old document ([archive link](http://archive.is/dNclX)), but `retrieveStyleModule` isn't, as far as I can tell.

**Comment by cormacrelf** [comment]
And the CSL-M document is 404 at the moment.

https://citeproc-js.readthedocs.io/en/latest/csl-m/index.html

(Anyone who wants to read the docs manually can browse the .rst files on GitHub, they are formatted like Markdown is.)

**Comment by thesmithee** [comment]
To add to that, seems like https://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html is also 404-ing at the moment (exists in the source, ofc). A problem with the RTD build perhaps?

**Comment by fbennett** [comment]
When it rains, it pours. The [CSL-JSON](https://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html) and [CSL-M](https://citeproc-js.readthedocs.io/en/latest/csl-m/index.html) pages are back up. Re the cause, I added documentation on a few new CSL-M features yesterday, and treatment of one of the doc builder's settings was apparently tightened since the last build, causing those two pages to go poof. Many thanks to all for raising the flag so quickly.

On the original topic, it does look like the extended `sys` functions remain to be written up. The information on abbreviations in the old manual was spun off to an [Abbrevs Filter manual](https://abbrevs-filter.readthedocs.io/en/latest/) that should probably be prominently linked from both citeproc-js and Juris-M docs.

**Comment by thesmithee** [comment]
Thanks much for the speedy resolution! 😄
